version: '3'

services:
  redis:
    image: redis
    container_name: some-redis2
    ports: 
      - 6379:6379
    networks:
     - backendNetwork
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: a101ssafy
      MYSQL_DATABASE: horangitdb
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: a101ssafy
    ports:
      - 3306:3306
    networks:
     - backendNetwork
  springapi:
    image: openjdk:8
    container_name: springapi
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis
    volumes:
      - ./backend/target/project-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork
      - frontendNetwork
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - 8081:80
    depends_on:
      - springapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/:/usr/share/nginx/html
    networks:
      - frontendNetwork

networks:
  backendNetwork:
  frontendNetwork: