use horangitdb;

INSERT INTO district (name) value("서울특별시");
INSERT INTO district (name) value("부산광역시");
INSERT INTO district (name) value("대구광역시");
INSERT INTO district (name) value("인천광역시");
INSERT INTO district (name) value("광주광역시");
INSERT INTO district (name) value("대전광역시");
INSERT INTO district (name) value("울산광역시");
INSERT INTO district (name) value("세종특별자치시");
INSERT INTO district (name) value("경기도");
INSERT INTO district (name) value("강원도");
INSERT INTO district (name) value("충청북도");
INSERT INTO district (name) value("충청남도");
INSERT INTO district (name) value("전라북도");
INSERT INTO district (name) value("전라남도");
INSERT INTO district (name) value("경상북도");
INSERT INTO district (name) value("경상남도");
INSERT INTO district (name) value("제주특별자치도");

INSERT INTO si_gun_gu (district_id, name) values(1, "종로구");
INSERT INTO si_gun_gu (district_id, name) values(1, "중구");
INSERT INTO si_gun_gu (district_id, name) values(1, "용산구");
INSERT INTO si_gun_gu (district_id, name) values(1, "성동구");
INSERT INTO si_gun_gu (district_id, name) values(1, "광진구");
INSERT INTO si_gun_gu (district_id, name) values(1, "동대문구");
INSERT INTO si_gun_gu (district_id, name) values(1, "중랑구");
INSERT INTO si_gun_gu (district_id, name) values(1, "성북구");
INSERT INTO si_gun_gu (district_id, name) values(1, "강북구");
INSERT INTO si_gun_gu (district_id, name) values(1, "도봉구");
INSERT INTO si_gun_gu (district_id, name) values(1, "노원구");
INSERT INTO si_gun_gu (district_id, name) values(1, "은평구");
INSERT INTO si_gun_gu (district_id, name) values(1, "서대문구");
INSERT INTO si_gun_gu (district_id, name) values(1, "마포구");
INSERT INTO si_gun_gu (district_id, name) values(1, "양천구");
INSERT INTO si_gun_gu (district_id, name) values(1, "강서구");
INSERT INTO si_gun_gu (district_id, name) values(1, "구로구");
INSERT INTO si_gun_gu (district_id, name) values(1, "금천구");
INSERT INTO si_gun_gu (district_id, name) values(1, "영등포구");
INSERT INTO si_gun_gu (district_id, name) values(1, "동작구");
INSERT INTO si_gun_gu (district_id, name) values(1, "관악구");
INSERT INTO si_gun_gu (district_id, name) values(1, "서초구");
INSERT INTO si_gun_gu (district_id, name) values(1, "강남구");
INSERT INTO si_gun_gu (district_id, name) values(1, "송파구");
INSERT INTO si_gun_gu (district_id, name) values(1, "강동구");

INSERT INTO si_gun_gu (district_id, name) values(2, "중구");
INSERT INTO si_gun_gu (district_id, name) values(2, "서구");
INSERT INTO si_gun_gu (district_id, name) values(2, "동구");
INSERT INTO si_gun_gu (district_id, name) values(2, "영도구");
INSERT INTO si_gun_gu (district_id, name) values(2, "부산진구");
INSERT INTO si_gun_gu (district_id, name) values(2, "동래구");
INSERT INTO si_gun_gu (district_id, name) values(2, "남구");
INSERT INTO si_gun_gu (district_id, name) values(2, "북구");
INSERT INTO si_gun_gu (district_id, name) values(2, "강서구");
INSERT INTO si_gun_gu (district_id, name) values(2, "해운대구");
INSERT INTO si_gun_gu (district_id, name) values(2, "사하구");
INSERT INTO si_gun_gu (district_id, name) values(2, "금정구");
INSERT INTO si_gun_gu (district_id, name) values(2, "연제구");
INSERT INTO si_gun_gu (district_id, name) values(2, "수영구");
INSERT INTO si_gun_gu (district_id, name) values(2, "사상구");

INSERT INTO si_gun_gu (district_id, name) values(3, "중구");
INSERT INTO si_gun_gu (district_id, name) values(3, "동구");
INSERT INTO si_gun_gu (district_id, name) values(3, "서구");
INSERT INTO si_gun_gu (district_id, name) values(3, "남구");
INSERT INTO si_gun_gu (district_id, name) values(3, "북구");
INSERT INTO si_gun_gu (district_id, name) values(3, "수성구");
INSERT INTO si_gun_gu (district_id, name) values(3, "달서구");
INSERT INTO si_gun_gu (district_id, name) values(3, "달성군");

INSERT INTO si_gun_gu (district_id, name) values(4, "중구");
INSERT INTO si_gun_gu (district_id, name) values(4, "동구");
INSERT INTO si_gun_gu (district_id, name) values(4, "미추홀구");
INSERT INTO si_gun_gu (district_id, name) values(4, "연수구");
INSERT INTO si_gun_gu (district_id, name) values(4, "남동구");
INSERT INTO si_gun_gu (district_id, name) values(4, "부평구");
INSERT INTO si_gun_gu (district_id, name) values(4, "계양구");
INSERT INTO si_gun_gu (district_id, name) values(4, "서구");
INSERT INTO si_gun_gu (district_id, name) values(4, "강화군");
INSERT INTO si_gun_gu (district_id, name) values(4, "옹진군");

INSERT INTO si_gun_gu (district_id, name) values(5, "동구");
INSERT INTO si_gun_gu (district_id, name) values(5, "서구");
INSERT INTO si_gun_gu (district_id, name) values(5, "남구");
INSERT INTO si_gun_gu (district_id, name) values(5, "북구");
INSERT INTO si_gun_gu (district_id, name) values(5, "광산구");

INSERT INTO si_gun_gu (district_id, name) values(6, "동구");
INSERT INTO si_gun_gu (district_id, name) values(6, "중구");
INSERT INTO si_gun_gu (district_id, name) values(6, "서구");
INSERT INTO si_gun_gu (district_id, name) values(6, "유성구");
INSERT INTO si_gun_gu (district_id, name) values(6, "대덕구");

INSERT INTO si_gun_gu (district_id, name) values(7, "중구");
INSERT INTO si_gun_gu (district_id, name) values(7, "남구");
INSERT INTO si_gun_gu (district_id, name) values(7, "동구");
INSERT INTO si_gun_gu (district_id, name) values(7, "북구");
INSERT INTO si_gun_gu (district_id, name) values(7, "울주군");

INSERT INTO si_gun_gu (district_id, name) values(9, "수원시 장안구");
INSERT INTO si_gun_gu (district_id, name) values(9, "수원시 권선구");
INSERT INTO si_gun_gu (district_id, name) values(9, "수원시 팔달구");
INSERT INTO si_gun_gu (district_id, name) values(9, "수원시 영통구");
INSERT INTO si_gun_gu (district_id, name) values(9, "성남시 수정구");
INSERT INTO si_gun_gu (district_id, name) values(9, "성남시 중원구");
INSERT INTO si_gun_gu (district_id, name) values(9, "성남시 분당구");
INSERT INTO si_gun_gu (district_id, name) values(9, "안양시 만안구");
INSERT INTO si_gun_gu (district_id, name) values(9, "안양시 동안구");
INSERT INTO si_gun_gu (district_id, name) values(9, "안산시 상록구");
INSERT INTO si_gun_gu (district_id, name) values(9, "안산시 단원구");
INSERT INTO si_gun_gu (district_id, name) values(9, "용인시 처인구");
INSERT INTO si_gun_gu (district_id, name) values(9, "용인시 기흥구");
INSERT INTO si_gun_gu (district_id, name) values(9, "용인시 수지구");
INSERT INTO si_gun_gu (district_id, name) values(9, "고양시 덕양구");
INSERT INTO si_gun_gu (district_id, name) values(9, "고양시 일산동구");
INSERT INTO si_gun_gu (district_id, name) values(9, "고양시 일산서구");
INSERT INTO si_gun_gu (district_id, name) values(9, "의정부시");
INSERT INTO si_gun_gu (district_id, name) values(9, "동두천시");
INSERT INTO si_gun_gu (district_id, name) values(9, "구리시");
INSERT INTO si_gun_gu (district_id, name) values(9, "남양주시");
INSERT INTO si_gun_gu (district_id, name) values(9, "파주시");
INSERT INTO si_gun_gu (district_id, name) values(9, "양주시");
INSERT INTO si_gun_gu (district_id, name) values(9, "포천시");
INSERT INTO si_gun_gu (district_id, name) values(9, "부천시");
INSERT INTO si_gun_gu (district_id, name) values(9, "광명시");
INSERT INTO si_gun_gu (district_id, name) values(9, "평택시");
INSERT INTO si_gun_gu (district_id, name) values(9, "과천시");
INSERT INTO si_gun_gu (district_id, name) values(9, "오산시");
INSERT INTO si_gun_gu (district_id, name) values(9, "시흥시");
INSERT INTO si_gun_gu (district_id, name) values(9, "군포시");
INSERT INTO si_gun_gu (district_id, name) values(9, "의왕시");
INSERT INTO si_gun_gu (district_id, name) values(9, "하남시");
INSERT INTO si_gun_gu (district_id, name) values(9, "이천시");
INSERT INTO si_gun_gu (district_id, name) values(9, "안성시");
INSERT INTO si_gun_gu (district_id, name) values(9, "김포시");
INSERT INTO si_gun_gu (district_id, name) values(9, "화성시");
INSERT INTO si_gun_gu (district_id, name) values(9, "광주시");
INSERT INTO si_gun_gu (district_id, name) values(9, "여주시");
INSERT INTO si_gun_gu (district_id, name) values(9, "양평군");
INSERT INTO si_gun_gu (district_id, name) values(9, "연천군");
INSERT INTO si_gun_gu (district_id, name) values(9, "가평군");

INSERT INTO si_gun_gu (district_id, name) values(10, "춘천시");
INSERT INTO si_gun_gu (district_id, name) values(10, "원주시");
INSERT INTO si_gun_gu (district_id, name) values(10, "강릉시");
INSERT INTO si_gun_gu (district_id, name) values(10, "동해시");
INSERT INTO si_gun_gu (district_id, name) values(10, "태백시");
INSERT INTO si_gun_gu (district_id, name) values(10, "속초시");
INSERT INTO si_gun_gu (district_id, name) values(10, "삼척시");
INSERT INTO si_gun_gu (district_id, name) values(10, "홍천군");
INSERT INTO si_gun_gu (district_id, name) values(10, "횡성군");
INSERT INTO si_gun_gu (district_id, name) values(10, "영월군");
INSERT INTO si_gun_gu (district_id, name) values(10, "평창군");
INSERT INTO si_gun_gu (district_id, name) values(10, "정선군");
INSERT INTO si_gun_gu (district_id, name) values(10, "철원군");
INSERT INTO si_gun_gu (district_id, name) values(10, "화천군");
INSERT INTO si_gun_gu (district_id, name) values(10, "양구군");
INSERT INTO si_gun_gu (district_id, name) values(10, "인제군");
INSERT INTO si_gun_gu (district_id, name) values(10, "고성군");
INSERT INTO si_gun_gu (district_id, name) values(10, "양양군");

INSERT INTO si_gun_gu (district_id, name) values(11, "청주시 상당구");
INSERT INTO si_gun_gu (district_id, name) values(11, "청주시 흥덕구");
INSERT INTO si_gun_gu (district_id, name) values(11, "청주시 서원구");
INSERT INTO si_gun_gu (district_id, name) values(11, "청주시 청원구");
INSERT INTO si_gun_gu (district_id, name) values(11, "충주시");
INSERT INTO si_gun_gu (district_id, name) values(11, "제천시");
INSERT INTO si_gun_gu (district_id, name) values(11, "보은군");
INSERT INTO si_gun_gu (district_id, name) values(11, "옥천군");
INSERT INTO si_gun_gu (district_id, name) values(11, "영동군");
INSERT INTO si_gun_gu (district_id, name) values(11, "증평군");
INSERT INTO si_gun_gu (district_id, name) values(11, "진천군");
INSERT INTO si_gun_gu (district_id, name) values(11, "괴산군");
INSERT INTO si_gun_gu (district_id, name) values(11, "음성군");
INSERT INTO si_gun_gu (district_id, name) values(11, "단양군");

INSERT INTO si_gun_gu (district_id, name) values(12, "천안시 동남구");
INSERT INTO si_gun_gu (district_id, name) values(12, "천안시 서북구");
INSERT INTO si_gun_gu (district_id, name) values(12, "공주시");
INSERT INTO si_gun_gu (district_id, name) values(12, "보령시");
INSERT INTO si_gun_gu (district_id, name) values(12, "아산시");
INSERT INTO si_gun_gu (district_id, name) values(12, "서산시");
INSERT INTO si_gun_gu (district_id, name) values(12, "논산시");
INSERT INTO si_gun_gu (district_id, name) values(12, "계룡시");
INSERT INTO si_gun_gu (district_id, name) values(12, "당진시");
INSERT INTO si_gun_gu (district_id, name) values(12, "금산군");
INSERT INTO si_gun_gu (district_id, name) values(12, "부여군");
INSERT INTO si_gun_gu (district_id, name) values(12, "서천군");
INSERT INTO si_gun_gu (district_id, name) values(12, "청양군");
INSERT INTO si_gun_gu (district_id, name) values(12, "홍성군");
INSERT INTO si_gun_gu (district_id, name) values(12, "예산군");
INSERT INTO si_gun_gu (district_id, name) values(12, "태안군");

INSERT INTO si_gun_gu (district_id, name) values(13, "전주시 완산구");
INSERT INTO si_gun_gu (district_id, name) values(13, "전주시 덕진구");
INSERT INTO si_gun_gu (district_id, name) values(13, "군산시");
INSERT INTO si_gun_gu (district_id, name) values(13, "익산시");
INSERT INTO si_gun_gu (district_id, name) values(13, "정읍시");
INSERT INTO si_gun_gu (district_id, name) values(13, "남원시");
INSERT INTO si_gun_gu (district_id, name) values(13, "김제시");
INSERT INTO si_gun_gu (district_id, name) values(13, "완주군");
INSERT INTO si_gun_gu (district_id, name) values(13, "진안군");
INSERT INTO si_gun_gu (district_id, name) values(13, "무주군");
INSERT INTO si_gun_gu (district_id, name) values(13, "장수군");
INSERT INTO si_gun_gu (district_id, name) values(13, "임실군");
INSERT INTO si_gun_gu (district_id, name) values(13, "순창군");
INSERT INTO si_gun_gu (district_id, name) values(13, "고창군");
INSERT INTO si_gun_gu (district_id, name) values(13, "부안군");

INSERT INTO si_gun_gu (district_id, name) values(14, "목포시");
INSERT INTO si_gun_gu (district_id, name) values(14, "여수시");
INSERT INTO si_gun_gu (district_id, name) values(14, "순천시");
INSERT INTO si_gun_gu (district_id, name) values(14, "나주시");
INSERT INTO si_gun_gu (district_id, name) values(14, "광양시");
INSERT INTO si_gun_gu (district_id, name) values(14, "담양군");
INSERT INTO si_gun_gu (district_id, name) values(14, "곡성군");
INSERT INTO si_gun_gu (district_id, name) values(14, "구례군");
INSERT INTO si_gun_gu (district_id, name) values(14, "고흥군");
INSERT INTO si_gun_gu (district_id, name) values(14, "보성군");
INSERT INTO si_gun_gu (district_id, name) values(14, "화순군");
INSERT INTO si_gun_gu (district_id, name) values(14, "장흥군");
INSERT INTO si_gun_gu (district_id, name) values(14, "강진군");
INSERT INTO si_gun_gu (district_id, name) values(14, "해남군");
INSERT INTO si_gun_gu (district_id, name) values(14, "영암군");
INSERT INTO si_gun_gu (district_id, name) values(14, "무안군");
INSERT INTO si_gun_gu (district_id, name) values(14, "함평군");
INSERT INTO si_gun_gu (district_id, name) values(14, "영광군");
INSERT INTO si_gun_gu (district_id, name) values(14, "장성군");
INSERT INTO si_gun_gu (district_id, name) values(14, "완두군");
INSERT INTO si_gun_gu (district_id, name) values(14, "진도군");
INSERT INTO si_gun_gu (district_id, name) values(14, "신안군");

INSERT INTO si_gun_gu (district_id, name) values(15, "포항시 남구");
INSERT INTO si_gun_gu (district_id, name) values(15, "포항시 북구");
INSERT INTO si_gun_gu (district_id, name) values(15, "경주시");
INSERT INTO si_gun_gu (district_id, name) values(15, "김천시");
INSERT INTO si_gun_gu (district_id, name) values(15, "안동시");
INSERT INTO si_gun_gu (district_id, name) values(15, "구미시");
INSERT INTO si_gun_gu (district_id, name) values(15, "영주시");
INSERT INTO si_gun_gu (district_id, name) values(15, "영천시");
INSERT INTO si_gun_gu (district_id, name) values(15, "상주시");
INSERT INTO si_gun_gu (district_id, name) values(15, "문경시");
INSERT INTO si_gun_gu (district_id, name) values(15, "경산시");
INSERT INTO si_gun_gu (district_id, name) values(15, "근위군");
INSERT INTO si_gun_gu (district_id, name) values(15, "의성군");
INSERT INTO si_gun_gu (district_id, name) values(15, "청송군");
INSERT INTO si_gun_gu (district_id, name) values(15, "영양군");
INSERT INTO si_gun_gu (district_id, name) values(15, "영덕군");
INSERT INTO si_gun_gu (district_id, name) values(15, "청도군");
INSERT INTO si_gun_gu (district_id, name) values(15, "고령군");
INSERT INTO si_gun_gu (district_id, name) values(15, "성주군");
INSERT INTO si_gun_gu (district_id, name) values(15, "칠곡군");
INSERT INTO si_gun_gu (district_id, name) values(15, "예천군");
INSERT INTO si_gun_gu (district_id, name) values(15, "봉화군");
INSERT INTO si_gun_gu (district_id, name) values(15, "울진군");
INSERT INTO si_gun_gu (district_id, name) values(15, "울릉군");

INSERT INTO si_gun_gu (district_id, name) values(16, "창원시 의창구");
INSERT INTO si_gun_gu (district_id, name) values(16, "창원시 성산구");
INSERT INTO si_gun_gu (district_id, name) values(16, "창원시 마산합포구");
INSERT INTO si_gun_gu (district_id, name) values(16, "창원시 마산회원구");
INSERT INTO si_gun_gu (district_id, name) values(16, "창원시 진해구");
INSERT INTO si_gun_gu (district_id, name) values(16, "진주시");
INSERT INTO si_gun_gu (district_id, name) values(16, "통영시");
INSERT INTO si_gun_gu (district_id, name) values(16, "사천시");
INSERT INTO si_gun_gu (district_id, name) values(16, "김해시");
INSERT INTO si_gun_gu (district_id, name) values(16, "밀양시");
INSERT INTO si_gun_gu (district_id, name) values(16, "거제시");
INSERT INTO si_gun_gu (district_id, name) values(16, "양산시");
INSERT INTO si_gun_gu (district_id, name) values(16, "의령군");
INSERT INTO si_gun_gu (district_id, name) values(16, "함안군");
INSERT INTO si_gun_gu (district_id, name) values(16, "창녕군");
INSERT INTO si_gun_gu (district_id, name) values(16, "고성군");
INSERT INTO si_gun_gu (district_id, name) values(16, "남해군");
INSERT INTO si_gun_gu (district_id, name) values(16, "하동군");
INSERT INTO si_gun_gu (district_id, name) values(16, "산청군");
INSERT INTO si_gun_gu (district_id, name) values(16, "함양군");
INSERT INTO si_gun_gu (district_id, name) values(16, "거창군");
INSERT INTO si_gun_gu (district_id, name) values(16, "합천군");